name: Run Maestro tests

on:
  workflow_run:
    workflows: [EAS Build (Test)]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          registry-url: https://registry.npmjs.org
          scope: "@tendrel"
      - name: Install Dependencies
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun install --frozen-lockfile
      - name: Install dcd
        run: bun install -g @devicecloud.dev/dcd@latest

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Run tests
        run: DCD_API_KEY=${{secrets.DCD_API_KEY}} EXPO_TOKEN=${{secrets.EXPO_TOKEN}} PASSWORD=${{secrets.TEST_PASSWORD}} bun scripts/run-mobile-tests.ts --platform iOS --commitHash ${{ github.event.workflow_run.head_sha}}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.run-tests.result == 'failure' || needs.run-tests.result == 'timed_out') }}
    needs:
      - run-tests
    steps:
      - uses: actions/checkout@v2
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # tendrel-tweets channel
          channel-id: 'C041PBUKSJF'
          slack-message: "🚨 Checklist Maestro test failures 🚨 \n Commit: ${{ github.sha }} \n https://console.devicecloud.dev/results"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
